spring.application.name=${APPLICATION_NAME}


# Configuration MongoDB
spring.data.mongodb.database=${MONGO_DB_NAME}
spring.data.mongodb.uri=${MONGO_DB_URI}


# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXP}

# Resend
resend.email=${RESEND_EMAIL}
resend.api_key=${RESEND_API_KEY}

#Domain
domain=${DOMAIN}

# Spring Security
spring.security.user.name=${USERNAME_ADMIN}
spring.security.user.password=${PASSWORD_ADMIN}


#Cloudflare
cloudflare.api=${CLOUDFLARE_S3_API}
cloudflare.bucket_name=${CLOUDFLARE_BUCKET_NAME}
cloudflare.access_key=${CLOUDFLARE_ACCESS_KEY}
cloudflare.secret_key=${CLOUDFLARE_SECRET_KEY}
cloudflare.token_value=${CLOUDFLARE_TOKEN_VALUE}

