spring.application.name=MoneyBuddy
logging.level.org.springframework=DEBUG
logging.level.moneybuddy.fr=DEBUG

#Server
server.port=8080
server.address=0.0.0.0

#Actuator & Metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized

# Configuration MongoDB
spring.data.mongodb.database=MoneyBuddy
spring.data.mongodb.uri=mongodb+srv://ezzerqtiryan:LGt3HPa05khzuvPi@moneybuddy.wnapins.mongodb.net/?retryWrites=true&w=majority&appName=MoneyBuddy

# JWT
jwt.secret=sho6SNdtMTm3ZceSP2FnEYwwRrz0CC7avT+JQeaaM/g=
jwt.expiration=86400000

# Resend
resend.email=@moneybuddy.fr
resend.api_key=re_3hfSsJi3_F1oSLDxkGfyy2V1kdiPiyLJu

#Domain
domain=moneybuddy.fr

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin

#Cloudflare
cloudflare.api=https://ca51dc07ee5ac988536fffbfa31270d1.r2.cloudflarestorage.com
cloudflare.bucket_name=moneybuddy
cloudflare.access_key=56d8fee65c33da0383f681fb2c766a0b
cloudflare.secret_key=b44c5345c33238440bcc815d7eb6640d4871ae3352b3fb06b4f30ed65250a0a1
cloudflare.token_value=cdg-DVvRJK75ylu5KrajEs0GHw-j2fabVaKl3ynM

#Discord
discord.application.id=1448970510061932606
discord.public.key=00962db5702c6defbf12a74741110025dd748ccb2805019edee95e2c2c5b95e4
discord.application.token=MTQ0ODk3MDUxMDA2MTkzMjYwNg.G5Ghkk.KXw3WKeFtBbD6cE6Bs0sL8oXCPe08DPXntFalU
discord.channel.monitoring.auth=1448992254671847517
discord.channel.monitoring.errors=1449044482363363389
discord.channel.monitoring.basic=1450841770895216700
