spring.application.name=${APPLICATION_NAME:MoneyBuddy}

#Prometheus 
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
management.endpoint.prometheus.enabled=${MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED}
management.metrics.export.prometheus.enabled=${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED}

# Configuration MongoDB
spring.data.mongodb.database=${MONGO_DB_NAME}
spring.data.mongodb.uri=${MONGO_DB_URI}


# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXP}

# Resend
resend.email=${RESEND_EMAIL}
resend.api_key=${RESEND_API_KEY}

#Domain
domain=${DOMAIN}

# Spring Security
spring.security.user.name=${USERNAME_ADMIN}
spring.security.user.password=${PASSWORD_ADMIN}

#Cloudflare
cloudflare.api=${CLOUDFLARE_S3_API}
cloudflare.bucket_name=${CLOUDFLARE_BUCKET_NAME}
cloudflare.access_key=${CLOUDFLARE_ACCESS_KEY}
cloudflare.secret_key=${CLOUDFLARE_SECRET_KEY}
cloudflare.token_value=${CLOUDFLARE_TOKEN_VALUE}


#Discord
discord.application.id=${DISCORD_APPLICATION_ID}
discord.public.key=${DISCORD_PUBLIC_KEY}
discord.application.token=${DISCORD_APPLICATION_TOKEN}
discord.channel.monitoring.auth=${DISCORD_CHANNEL_MONITORING_AUTH}
discord.channel.monitoring.errors=${DISCORD_CHANNEL_MONITORING_ERRORS}
discord.channel.monitoring.basic=${DISCORD_CHANNEL_MONITORING_BASIC}